//------------ CL CLOTHING VENDOR---------------

GLOBAL_LIST_INIT(cm_vending_clothing_cia, list(
	list("套装与内搭（任选5件）", 0, null, null, null),
	list("黑色西装裤", 0, /obj/item/clothing/under/liaison_suit/black, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_RECOMMENDED),
	list("黑色西装裙", 0, /obj/item/clothing/under/liaison_suit/black/skirt, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_RECOMMENDED),
	list("蓝色西装裤", 0, /obj/item/clothing/under/liaison_suit/blue, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("棕色西装裤", 0, /obj/item/clothing/under/liaison_suit/brown, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("白色西装裤", 0, /obj/item/clothing/under/liaison_suit/corporate_formal, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("灰色西装裤", 0, /obj/item/clothing/under/detective/grey, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("破旧套装", 0, /obj/item/clothing/under/detective/neutral, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("乡村俱乐部套装", 0, /obj/item/clothing/under/liaison_suit/ivy, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("商务休闲装", 0, /obj/item/clothing/under/liaison_suit/field, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("商务休闲裙", 0, /obj/item/clothing/under/liaison_suit/field/skirt, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("简约白衬衫，黑色长裤", 0, /obj/item/clothing/under/sl_suit, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("简约白衬衫，蓝色长裤", 0, /obj/item/clothing/under/lawyer/bluesuit, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("黑色定制西装", 0, /obj/item/clothing/under/suit_jacket, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("勃艮第定制西装", 0, /obj/item/clothing/under/suit_jacket/burgundy, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("炭黑定制西装", 0, /obj/item/clothing/under/suit_jacket/charcoal, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("海军定制西装", 0, /obj/item/clothing/under/suit_jacket/navy, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("格纹定制西装", 0, /obj/item/clothing/under/suit_jacket/checkered, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("墨黑行政套装", 0, /obj/item/clothing/under/suit_jacket/really_black, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("女性纯黑行政套装", 0, /obj/item/clothing/under/suit_jacket/female, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("灰色工作服", 0, /obj/item/clothing/under/colonist/workwear, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("卡其色工作服", 0, /obj/item/clothing/under/colonist/workwear/khaki, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("粉色工作服", 0, /obj/item/clothing/under/colonist/workwear/pink, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("绿色工作服", 0, /obj/item/clothing/under/colonist/workwear/green, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),
	list("蓝色工作服", 0, /obj/item/clothing/under/colonist/workwear/blue, CIVILIAN_CAN_BUY_UNIFORM, VENDOR_ITEM_REGULAR),

	list("套装（选择5件）", 0, null, null, null),
	list("黑色西装外套", 0, /obj/item/clothing/suit/storage/jacket/marine/corporate/black, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_RECOMMENDED),
	list("卡其色西装外套", 0, /obj/item/clothing/suit/storage/jacket/marine/corporate, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("棕色西装外套", 0, /obj/item/clothing/suit/storage/jacket/marine/corporate/brown, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("蓝色西装外套", 0, /obj/item/clothing/suit/storage/jacket/marine/corporate/blue, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("正式西装外套", 0, /obj/item/clothing/suit/storage/jacket/marine/corporate/formal, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("黑色时尚西装外套", 0, /obj/item/clothing/suit/storage/jacket/marine/lawyer/blackjacket, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("蓝色花式西装外套", 0, /obj/item/clothing/suit/storage/jacket/marine/lawyer/bluejacket, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("紫色花式西装外套", 0, /obj/item/clothing/suit/storage/jacket/marine/lawyer/purpjacket, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("红色花式西装外套", 0, /obj/item/clothing/suit/storage/jacket/marine/lawyer/redjacket, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("棕色花式西装外套", 0, /obj/item/clothing/suit/storage/jacket/marine/lawyer/brown, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("浅棕色花式西装外套", 0, /obj/item/clothing/suit/storage/jacket/marine/lawyer/light_brown, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("灰色轰炸机夹克", 0, /obj/item/clothing/suit/storage/jacket/marine/bomber/grey, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("红色轰炸机夹克", 0, /obj/item/clothing/suit/storage/jacket/marine/bomber/red, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("卡其色轰炸机夹克", 0, /obj/item/clothing/suit/storage/jacket/marine/bomber, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("棕色轰炸机夹克", 0, /obj/item/clothing/suit/storage/bomber, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("黑色轰炸机夹克", 0, /obj/item/clothing/suit/storage/bomber/alt, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("棕色风衣", 0, /obj/item/clothing/suit/storage/windbreaker/windbreaker_brown, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("灰色风衣", 0, /obj/item/clothing/suit/storage/windbreaker/windbreaker_gray, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("绿色风衣", 0, /obj/item/clothing/suit/storage/windbreaker/windbreaker_green, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("棕色涤纶夹克", 0, /obj/item/clothing/suit/storage/snow_suit/hybrisa/polyester_jacket_brown, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("蓝色涤纶夹克", 0, /obj/item/clothing/suit/storage/snow_suit/hybrisa/polyester_jacket_blue, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("红色涤纶夹克", 0, /obj/item/clothing/suit/storage/snow_suit/hybrisa/polyester_jacket_red, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("远征风衣", 0, /obj/item/clothing/suit/storage/windbreaker/windbreaker_covenant, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("米色风衣", 0, /obj/item/clothing/suit/storage/CMB/trenchcoat, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("棕色风衣", 0, /obj/item/clothing/suit/storage/CMB/trenchcoat/brown, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("灰色风衣", 0, /obj/item/clothing/suit/storage/CMB/trenchcoat/grey, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("白大褂", 0, /obj/item/clothing/suit/storage/labcoat, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("实验服，棕色", 0, /obj/item/clothing/suit/storage/labcoat/brown, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("灰色背心", 0, /obj/item/clothing/suit/storage/jacket/marine/vest/grey, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("棕色背心", 0, /obj/item/clothing/suit/storage/jacket/marine/vest, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),
	list("棕褐色背心", 0, /obj/item/clothing/suit/storage/jacket/marine/vest/tan, CIVILIAN_CAN_BUY_SUIT, VENDOR_ITEM_REGULAR),

	list("帽子（选择5顶）", 0, null, null, null),
	list("棕褐色贝雷帽", 0, /obj/item/clothing/head/beret/civilian, CIVILIAN_CAN_BUY_HAT, VENDOR_ITEM_REGULAR),
	list("棕色贝雷帽", 0, /obj/item/clothing/head/beret/civilian/brown, CIVILIAN_CAN_BUY_HAT, VENDOR_ITEM_REGULAR),
	list("黑色贝雷帽", 0, /obj/item/clothing/head/beret/civilian/black, CIVILIAN_CAN_BUY_HAT, VENDOR_ITEM_REGULAR),
	list("白色贝雷帽", 0, /obj/item/clothing/head/beret/civilian/white, CIVILIAN_CAN_BUY_HAT, VENDOR_ITEM_REGULAR),
	list("棕褐色软呢帽", 0, /obj/item/clothing/head/fedora, CIVILIAN_CAN_BUY_HAT, VENDOR_ITEM_REGULAR),
	list("棕色软呢帽", 0, /obj/item/clothing/head/fedora/brown, CIVILIAN_CAN_BUY_HAT, VENDOR_ITEM_REGULAR),
	list("灰色软呢帽", 0, /obj/item/clothing/head/fedora/grey, CIVILIAN_CAN_BUY_HAT, VENDOR_ITEM_REGULAR),
	list("牛仔帽，棕色", 0, /obj/item/clothing/head/cowboy, CIVILIAN_CAN_BUY_HAT, VENDOR_ITEM_REGULAR),
	list("牛仔帽，浅棕色", 0, /obj/item/clothing/head/cowboy/light, CIVILIAN_CAN_BUY_HAT, VENDOR_ITEM_REGULAR),

	list("眼镜（选择2副）", 0, null, null, null),
	list("比美克斯墨镜", 0, /obj/item/clothing/glasses/sunglasses/big, CIVILIAN_CAN_BUY_GLASSES, VENDOR_ITEM_RECOMMENDED),
	list("青铜飞行员墨镜", 0, /obj/item/clothing/glasses/sunglasses/aviator, CIVILIAN_CAN_BUY_GLASSES, VENDOR_ITEM_REGULAR),
	list("银色飞行员墨镜", 0, /obj/item/clothing/glasses/sunglasses/aviator/silver, CIVILIAN_CAN_BUY_GLASSES, VENDOR_ITEM_REGULAR),
	list("太阳镜", 0, /obj/item/clothing/glasses/sunglasses, CIVILIAN_CAN_BUY_GLASSES, VENDOR_ITEM_REGULAR),
	list("处方太阳镜", 0, /obj/item/clothing/glasses/sunglasses/prescription, CIVILIAN_CAN_BUY_GLASSES, VENDOR_ITEM_REGULAR),
	list("处方眼镜", 0, /obj/item/clothing/glasses/regular/hipster, CIVILIAN_CAN_BUY_GLASSES, VENDOR_ITEM_REGULAR),
	list("华丽单片眼镜", 0, /obj/item/clothing/glasses/monocle, CIVILIAN_CAN_BUY_GLASSES, VENDOR_ITEM_REGULAR),

	list("鞋子（选择2双）", 0, null, null, null),
	list("系带鞋，黑色", 0, /obj/item/clothing/shoes/laceup, CIVILIAN_CAN_BUY_SHOES, VENDOR_ITEM_RECOMMENDED),
	list("系带鞋，棕色", 0, /obj/item/clothing/shoes/laceup/brown, CIVILIAN_CAN_BUY_SHOES, VENDOR_ITEM_REGULAR),
	list("精美皮鞋", 0, /obj/item/clothing/shoes/leather/fancy, CIVILIAN_CAN_BUY_SHOES, VENDOR_ITEM_REGULAR),
	list("运动鞋，黑色", 0, /obj/item/clothing/shoes/black, CIVILIAN_CAN_BUY_SHOES, VENDOR_ITEM_REGULAR),
	list("擦亮的鞋子", 0, /obj/item/clothing/shoes/veteran/pmc/knife, CIVILIAN_CAN_BUY_SHOES, VENDOR_ITEM_REGULAR),

	list("手套（选择2件）", 0, null, null, null),
	list("黑手套", 0, /obj/item/clothing/gloves/black, CIVILIAN_CAN_BUY_GLOVES, VENDOR_ITEM_RECOMMENDED),
	list("棕色手套", 0, /obj/item/clothing/gloves/brown, CIVILIAN_CAN_BUY_GLOVES, VENDOR_ITEM_REGULAR),
	list("礼服手套", 0, /obj/item/clothing/gloves/marine/dress, CIVILIAN_CAN_BUY_GLOVES, VENDOR_ITEM_REGULAR),
	list("黑色皮手套", 0, /obj/item/clothing/gloves/black_leather, CIVILIAN_CAN_BUY_GLOVES, VENDOR_ITEM_RECOMMENDED),

	list("配件（选择5件）", 0, null, null, null),
	list("黑领结", 0, /obj/item/clothing/accessory/tie/black, CIVILIAN_CAN_BUY_ACCESSORY, VENDOR_ITEM_RECOMMENDED),
	list("红领带", 0, /obj/item/clothing/accessory/tie/red, CIVILIAN_CAN_BUY_ACCESSORY, VENDOR_ITEM_REGULAR),
	list("紫色领带", 0, /obj/item/clothing/accessory/tie/purple, CIVILIAN_CAN_BUY_ACCESSORY, VENDOR_ITEM_REGULAR),
	list("蓝色领带", 0, /obj/item/clothing/accessory/tie, CIVILIAN_CAN_BUY_ACCESSORY, VENDOR_ITEM_REGULAR),
	list("绿领带", 0, /obj/item/clothing/accessory/tie/green, CIVILIAN_CAN_BUY_ACCESSORY, VENDOR_ITEM_REGULAR),
	list("金领带", 0, /obj/item/clothing/accessory/tie/gold, CIVILIAN_CAN_BUY_ACCESSORY, VENDOR_ITEM_REGULAR),
	list("特殊领带", 0, /obj/item/clothing/accessory/tie/horrible, CIVILIAN_CAN_BUY_ACCESSORY, VENDOR_ITEM_REGULAR),
))

/obj/structure/machinery/cm_vending/clothing/cia
	name = "\improper UACQS 衣橱"
	desc = "一个衣柜，装有UACQS管理员所需的所有衣物。"
	icon_state = "wardrobe_vendor"
	vendor_theme = VENDOR_THEME_USCM
	show_points = FALSE
	req_access = list()
	vendor_role = JOB_CIA_ROLES_LIST

/obj/structure/machinery/cm_vending/clothing/cia/get_listed_products(mob/user)
	return GLOB.cm_vending_clothing_cia
