/mob/living/simple_animal/small/lizard
	name = "蜥蜴"
	desc = "一只可爱的小蜥蜴。"
	icon = 'icons/mob/critter.dmi'
	icon_state = "lizard"
	icon_living = "lizard"
	icon_dead = "lizard-dead"
	mob_size = MOB_SIZE_SMALL
	speak_emote = list("hisses")
	health = 5
	maxHealth = 5
	attacktext = "bites"
	attacktext = "bites"
	melee_damage_lower = 1
	melee_damage_upper = 2
	response_help  = "pets"
	response_disarm = "shoos"
	response_harm   = "stomps on"
	black_market_value = 50
	dead_black_market_value = 0
